=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/schema/element-schema.json
{
    "$schema": "http://json-schema.org/draft-07/#",
    "name": "bse_element_basis_set",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing how a element-based basis set is composed",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_name",
        "basis_set_description",
        "basis_set_elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "element" ]
                },
                "schema_version": {
                    "description": "Version of the BSE element basis set schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Data for a single element in the basis set",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [ "element_components" ],
                    "properties": {
                        "element_references": {
                            "description": "Citation/Reference information for this element",
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        },
                        "element_components": {
                            "description": "Component files for this element",
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== MolSSI-BSE/basis_set_exchange/bse/data/pople/5-21G.0.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "5-21G",
    "basis_set_description": "5-21G valence double-zeta basis set",
    "basis_set_elements": {
        "3": {
            "element_components": [
                "pople/5-21G_dill1975a.0.json"
            ]
        },
        "4": {
            "element_components": [
                "pople/5-21G_binkley1977a.0.json"
            ]
        }
    }
}
