=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/schema/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_metadata",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing metadata for a single basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "names",
        "tags",
        "family",
        "description",
        "role",
        "auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "metadata" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "names": {
            "description": "Common names/capitalization of the basis set",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": { "type": "string" }
        },
        "tags": {
            "description": "Feature tags (for internal use/marking)",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string",
                "enum": ["deprecated"]
            }
        },
        "family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "role": {
            "description": "Role that this basis plays in a calculation",
            "type": "string",
            "enum": [ "orbital", "rifit", "optri", "jkfit", "jfit", "admmfit", "dftxfit", "dftjfit"]
        },
        "auxiliaries": {
            "description": "Auxiliary basis sets (fitting, etc) and how their role with this basis",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "jfit" : { "type": "string" },
                "jkfit" : { "type": "string" },
                "rifit" : { "type": "string" },
                "optri" : { "type": "string" },
                "admmfit" : { "type": "string" },
                "dftxfit": { "type": "string" },
                "dftjfit": { "type": "string" }
            }
        }
    }
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/cc-pVTZ-F12.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "cc-pVTZ-F12"
  ],
  "tags": [],
  "family": "dunning_f12",
  "description": "VTZ for explicitly correlated F12 variants of wavefunction methods",
  "role": "orbital",
  "auxiliaries": {
    "optri": "cc-pvtz-f12-optri"
  }
}

=== MolSSI-BSE/basis_set_exchange/basis_set_exchange/data/aug-cc-pwCVTZ-PP.metadata.json
{
  "molssi_bse_schema": {
    "schema_type": "metadata",
    "schema_version": "0.1"
  },
  "names": [
    "aug-cc-pwCVTZ-PP"
  ],
  "tags": [],
  "family": "dunning_pp",
  "description": "aug-cc-pwCVTZ-PP",
  "role": "orbital",
  "auxiliaries": {
    "rifit": "aug-cc-pwcvtz-pp-rifit",
    "optri": "aug-cc-pwcvtz-pp-optri"
  }
}
